name: Deploy to Shared Hosting

on:
  push:
    branches:
      - production
      - deployment

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: üöö Get latest code
        uses: actions/checkout@v4

      - name: ‚ö°Ô∏è Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: üì¶ Install Dependencies
        working-directory: ./pemuda-app
        run: |
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: üìÇ Sync pemuda-app (Application Code)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./pemuda-app/
          server-dir: /pemuda-app/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

      - name: üìÇ Sync public_html (Public Assets)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public_html/
          server-dir: /public_html/
